name: CI

on:
  push:
    branches: [ "main" ]  # Cuando haces push a la rama "main"
  pull_request:
    branches: [ "main" ]  # Cuando haces un pull request a la rama "main"
  workflow_dispatch:  # Para ejecutar manualmente desde la interfaz de GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos una m치quina virtual con Ubuntu para ejecutar las acciones

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Este paso descarga el c칩digo del repositorio

      # Cambiar al directorio de tu proyecto, donde est치 el package.json
      - name: Move to the correct directory
        run: cd giga-bot-main  # Cambiamos al directorio correcto dentro de la carpeta

      # Instalar dependencias con npm
      - name: Install dependencies
        run: npm install  # Instala las dependencias usando el package.json

      # Ejecutar tests (si tienes configurados)
      - name: Run tests
        run: npm test  # Ejecuta los tests si tienes alguna configuraci칩n de test
