name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cambia al directorio de tu proyecto
      - name: Move to the correct directory
        run: cd giga-bot-main

      # Instala las dependencias de tu proyecto
      - name: Install dependencies
        run: npm install

      # Ejecuta los tests (si tienes configurados)
      - name: Run tests
        run: npm test
